# -*- mode: ruby -*-
# vi: set ft=ruby :

# Centos Nodes
#===================#
# Ansible-Node01    

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 180  # Setting up 30 Minute Time Out
  config.vm.define "ansible-node01" do |cfg|
    cfg.vm.box = "centos/7"               # Indicating OS to provision
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node01"          # Name for Virtual Machine
    end
    cfg.vm.host_name = "ansible-node01"   # Host Name for Virtual Machine  
    cfg.vm.network "private_network", ip: "192.168.56.11"   # Network Configuration
    cfg.vm.network "forwarded_port", guest:22, host: 60011, auto_correct: true
    cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  end
end

# Ansible-Node02    
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 180  # Setting up 30 Minute Time Out
  config.vm.define "ansible-node02" do |cfg|
    cfg.vm.box = "centos/7"               # Indicating OS to provision
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node02"          # Name for Virtual Machine
    end
    cfg.vm.host_name = "ansible-node02"   # Host Name for Virtual Machine  
    cfg.vm.network "private_network", ip: "192.168.56.12"   # Network Configuration
    cfg.vm.network "forwarded_port", guest:22, host: 60012, auto_correct: true
    cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  end
end

# Ansible-Node03    
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 180  # Setting up 30 Minute Time Out
  config.vm.define "ansible-node03" do |cfg|
    cfg.vm.box = "centos/7"               # Indicating OS to provision
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node03"          # Name for Virtual Machine
    end
    cfg.vm.host_name = "ansible-node03"   # Host Name for Virtual Machine  
    cfg.vm.network "private_network", ip: "192.168.56.13"   # Network Configuration
    cfg.vm.network "forwarded_port", guest:22, host: 60013, auto_correct: true
    cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  end
end

#===================#
# Ansible Server    #
#===================#

Vagrant.configure("2") do |config|
  config.vm.define "ansible-server" do |cfg|
    cfg.vm.box = "centos/7"               # Indicating OS to provision
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Server"          # Name for Virtual Machine
    end
    cfg.vm.host_name = "ansible-server"   # Host Name for Virtual Machine  
    cfg.vm.network "private_network", ip: "192.168.56.10"   # Network Configuration
    cfg.vm.network "forwarded_port", guest:22, host: 60010, auto_correct: true, id: "ssh"
    # Shared Folder with Host
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", inline: "yum install epel-release -y"
    cfg.vm.provision "shell", inline: "yum install ansible -y"
    cfg.vm.provision "file", source: "ansible_env_ready.yml", destination: "ansible_env_ready.yml"
    cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
  end
end

